# Generated by Django 5.0.6 on 2024-06-03 23:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbcDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Rufnummer', 'Rufnummer'), ('Ansage', 'Ansage')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CallForwardingRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kopfnummer', models.IntegerField()),
                ('anfang', models.DateTimeField()),
                ('ende', models.DateTimeField()),
                ('dauer', models.DurationField()),
                ('erinnerung', models.BooleanField(default=False)),
                ('durchwahl', models.IntegerField()),
                ('ziel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samj.tbcdestination')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)])),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(1)])),
                ('number', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=5)),
                ('global_settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='samj.globalsettings')),
            ],
        ),
    ]
