# Generated by Django 5.0.6 on 2024-06-24 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samj", "0002_user_email_user_groups_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=50, validators=[django.core.validators.MinLengthValidator(1)]
            ),
        ),
    ]
