# Generated by Django 5.0.6 on 2024-06-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samj", "0004_alter_user_global_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
